# Generated by Django 5.2.6 on 2025-09-24 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('brand', models.CharField(default='', editable=False, max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('pesona', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(default='', editable=False, max_length=255)),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(default='', editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lingkar', models.FloatField(default=0, editable=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('review', models.SmallIntegerField(default=0)),
                ('reviewCount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
