# Generated by Django 5.2.6 on 2025-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(default='', editable=False, max_length=255)),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(default='', editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('lingkar', models.FloatField(default=0, editable=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('review', models.SmallIntegerField(default=0)),
                ('reviewCount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
