# Generated by Django 5.2.6 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('brand', models.CharField(default='', editable=False, max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
