# Generated by Django 5.2.6 on 2025-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=255)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('pesona', models.TextField(default='')),
            ],
        ),
    ]
