# Generated by Django 5.2.6 on 2025-11-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lingkar',
            new_name='size',
        ),
    ]
